# Alembic Configuration File
# This file does the following:
#
# 1. Sets the sqlalchemy.url driver to the location of your database
# 2. Records the location of migration files
# 3. Each .py file is loaded as a set of commands that configure
#    the State of a particular revision environment
#
# When you want to create a new database or upgrade, you would
# then invoke the command line.

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S

# The string value set here is passed to
# os.environ.get() and results
# in an instance of the Config class.
#
# sqlalchemy.url is the "connection string" for the
# your SQL database. driver://username:password@HOST/database
# This line is read from the environment as the value for
# sqlalchemy.url for the target database.
#
# For example:
sqlalchemy.url = postgresql://username:password@localhost/QTDA

[alembic]
# path to migration scripts
script_location = alembic

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
#file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# defaults to the current directory
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to datetime.datetime.now(datetime.timezone(datetime.timedelta(seconds=tz_offset)))
# Leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field that's auto-generated by the revision
# template; set to 0 to disable, leaving
# the entire slug unchanged
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# this is useful for Alembic, especially when used
# in a CI/CD pipeline, where the calling system only wants
# to know if run successfully, without caring
# to actually see revision scripts.
# sqlalchemy.echo can be true or false (with empty string as false).
sqlalchemy.echo = false

# the output encoding used when revision files
# output.encoding is defined for output of the migration file
# in case of it being non-utf8
output_encoding = utf-8

; sqlalchemy.url = postgresql://postgres:Lamvu123@localhost:5432/QTDA
sqlalchemy.url = postgresql+asyncpg://postgres:ntaPGSQL2005@localhost:5432/QTDA
